/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ZXDocument, ConfigValuesMap } from "./types";
import { isNodeVisible } from "./parser";

export function generateCHeader(doc: ZXDocument, values: ConfigValuesMap): string {
  let output = `/**\n * ZXConfig Generated C Header\n * This file is automatically generated. Do not edit directly.\n */\n\n`;
  output += `#ifndef ZXCONFIG_GENERATED_H\n#define ZXCONFIG_GENERATED_H\n\n`;

  for (const group of doc.groups) {
    output += `/* === Group: ${group.label} === */\n`;
    for (const opt of group.children) {
      const active = isNodeVisible(opt.id, doc, values);
      const val = values[opt.id] !== undefined ? values[opt.id] : opt.defaultValue;

      if (opt.description) {
        output += `/* ${opt.description} */\n`;
      }

      if (!active) {
        output += `/* #define CONFIG_${opt.id} -- disabled by visibility constraints */\n\n`;
      } else {
        if (opt.type === "bool") {
          output += `#define CONFIG_${opt.id} ${val ? "1" : "0"}\n\n`;
        } else if (opt.type === "int") {
          output += `#define CONFIG_${opt.id} ${val}\n\n`;
        } else if (opt.type === "string") {
          output += `#define CONFIG_${opt.id} "${String(val).replace(/"/g, '\\"')}"\n\n`;
        } else if (opt.type === "select") {
          output += `#define CONFIG_${opt.id}_${val} 1\n`;
          output += `#define CONFIG_${opt.id} "${val}"\n\n`;
        }
      }
    }
  }

  output += `#endif /* ZXCONFIG_GENERATED_H */\n`;
  return output;
}

export function generateRustModule(doc: ZXDocument, values: ConfigValuesMap): string {
  let output = `//! ZXConfig Generated Rust Modules\n//! Automatically generated. Do not edit directly.\n\n`;

  for (const group of doc.groups) {
    output += `// === Group: ${group.label} ===\n`;
    for (const opt of group.children) {
      const active = isNodeVisible(opt.id, doc, values);
      const val = values[opt.id] !== undefined ? values[opt.id] : opt.defaultValue;

      if (opt.description) {
        output += `/// ${opt.description}\n`;
      }

      if (!active) {
        output += `// pub const CONFIG_${opt.id}: ... is inactive by constraint rules\n\n`;
      } else {
        if (opt.type === "bool") {
          output += `pub const CONFIG_${opt.id}: bool = ${val ? "true" : "false"};\n\n`;
        } else if (opt.type === "int") {
          output += `pub const CONFIG_${opt.id}: i32 = ${val};\n\n`;
        } else if (opt.type === "string" || opt.type === "select") {
          output += `pub const CONFIG_${opt.id}: &str = "${String(val).replace(/"/g, '\\"')}";\n\n`;
        }
      }
    }
  }

  return output;
}

export function generateMakefile(doc: ZXDocument, values: ConfigValuesMap): string {
  let output = `# ZXConfig Generated Makefile Snippet\n# Automatically generated. Do not edit directly.\n\n`;

  for (const group of doc.groups) {
    output += `# === Group: ${group.label} ===\n`;
    for (const opt of group.children) {
      const active = isNodeVisible(opt.id, doc, values);
      const val = values[opt.id] !== undefined ? values[opt.id] : opt.defaultValue;

      if (!active) {
        output += `# CONFIG_${opt.id} is not set (inactive)\n`;
      } else {
        if (opt.type === "bool") {
          output += `CONFIG_${opt.id} := ${val ? "y" : "n"}\n`;
        } else if (opt.type === "int") {
          output += `CONFIG_${opt.id} := ${val}\n`;
        } else {
          output += `CONFIG_${opt.id} := ${val}\n`;
        }
      }
    }
    output += "\n";
  }

  return output;
}

export function generateDevEnv(doc: ZXDocument, values: ConfigValuesMap): string {
  let output = `# ZXConfig Generated Environment Variables\n\n`;

  for (const group of doc.groups) {
    output += `# --- ${group.label} ---\n`;
    for (const opt of group.children) {
      const active = isNodeVisible(opt.id, doc, values);
      const val = values[opt.id] !== undefined ? values[opt.id] : opt.defaultValue;

      if (!active) {
        output += `# CONFIG_${opt.id}=\n`;
      } else {
        output += `CONFIG_${opt.id}="${String(val).replace(/"/g, '\\"')}"\n`;
      }
    }
    output += "\n";
  }

  return output;
}

export function generateFormat(format: "c" | "rust" | "makefile" | "env", doc: ZXDocument, values: ConfigValuesMap): string {
  switch (format) {
    case "c":
      return generateCHeader(doc, values);
    case "rust":
      return generateRustModule(doc, values);
    case "makefile":
      return generateMakefile(doc, values);
    case "env":
      return generateDevEnv(doc, values);
    default:
      return "";
  }
}
